<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>firstLineMatch</key>
	<string>.*file format.*</string>
	<key>keyEquivalent</key>
	<string>^~@O</string>
	<key>name</key>
	<string>objdump</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(mul|str|ldr|lsl|add|sub|mov|lsr|b|bl|cmp|rsb|adc|push|mvn|bic|tst|ldm)(eq|le|gt|ne)?d?s?(w|t|h)?\b</string>
			<key>name</key>
			<string>support.function.objdump</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(ascii|asciiz|byte|data|double|float|half|kdata|ktext|space|text|word|set\s*(noat|at))\b</string>
			<key>name</key>
			<string>storage.type.objdump</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.(align|extern||globl)\b</string>
			<key>name</key>
			<string>storage.modifier.objdump</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.label.objdump</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-9a-f]+) &lt;([A-Za-z0-9_]+)&gt;:</string>
			<key>name</key>
			<string>meta.function.label.objdump</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.objdump</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(r[0-9][1-5]?|ip|lr|pc|sp|fp|sl)</string>
			<key>name</key>
			<string>variable.other.register.arm.objdump</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\.\d+\b</string>
			<key>name</key>
			<string>constant.numeric.float.objdump</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.objdump</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#(-?[0-9]+)</string>
			<key>name</key>
			<string>misc.constant.objdump.immediate</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.objdump.offset</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.objdump.name</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([0-9a-f]+) &lt;([A-Za-z0-9_]+)(\+0x[0-9a-f]+)?&gt;</string>
			<key>name</key>
			<string>misc.constant.objdump.reftarget</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-f0-9]{8}\b</string>
			<key>name</key>
			<string>entity.name.section.objdump.address</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([a-f0-9]+):	</string>
			<key>name</key>
			<string>entity.name.section.objdump</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.objdump</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.character.objdump</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>this needs to match pathnames to c (and more!) files - using a kludge at the moment.</string>
			<key>match</key>
			<string>((/[a-zA-Z0-9_\.\-\.]+)+\.[ch](pp)?:\d+)</string>
			<key>name</key>
			<string>comment.line.character.objdump.lineref</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-z_0-9]+\(\):</string>
			<key>name</key>
			<string>comment.line.character.objdump.funcname</string>
		</dict>
	</array>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>asm</string>
	</array>
	<key>scopeName</key>
	<string>source.objdump</string>
	<key>uuid</key>
	<string>7FD88C2E-6BE3-11D9-9A40-19A1242E4184</string>
</dict>
</plist>
